database:
  path: "users.db"
  path_init: "migrations/init.sql"
tg:
  token: "8034032425:AAG2u988cGUs-V3BBAnq8SWaxwGiIQCmRss"
deepfake:
  metadata:
    audio_threshold: 0.5
    original_threshold: 0.1
  eye_detection:
    shape_predictor_path: "./internal/domain/deepfake/utils/shape_predictor/shape_predictor_68_face_landmarks.dat"
    radius_min_para: 4.5
    radius_max_para: 2.0
    threshold_scale_left: 1.2
    threshold_scale_right: 1.2
    threshold_iou: 0.6
  nn_detection:
    threshold_conf: 0.7
    mesonet_path: './internal/domain/deepfake/utils/mesonet/weights/Meso4_DF.h5'
  step: 1
face_analysis:
  detector: "retinaface"
  model_name: "Facenet"